# Generated by Django 5.0.2 on 2024-02-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Expédiée', 'Expédiée'), ('Annulée', 'Annulée')], default='En attente', max_length=200)),
                ('order_type', models.CharField(choices=[('Réapprovisionnement', 'Réapprovisionnement'), ('Urgence', 'Urgence'), ('Régulière Automatique', 'Régulière Automatique')], default='Réapprovisionnement', max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('productId', models.IntegerField()),
                ('clientId', models.IntegerField()),
            ],
        ),
    ]
