# Generated by Django 4.2.9 on 2024-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Expédiée', 'Expédiée'), ('Annulée', 'Annulée')], default='En attente', max_length=200)),
                ('order_type', models.CharField(choices=[('En ligne', 'En ligne'), ('En personne', 'En personne')], default='En ligne', max_length=200)),
            ],
        ),
    ]
