# Generated by Django 5.0.2 on 2024-02-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('groups', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Expédiée', 'Expédiée'), ('Annulée', 'Annulée')], default='En attente', max_length=200)),
                ('order_type', models.CharField(choices=[('En ligne', 'En ligne'), ('En personne', 'En personne')], default='En ligne', max_length=200)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('marque', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('prix', models.BigIntegerField()),
                ('quantite_stock', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('indications', models.TextField(max_length=200)),
                ('mode_emploi', models.TextField(max_length=2000)),
                ('composition', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Produts',
        ),
        migrations.AddField(
            model_name='orders',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.product'),
        ),
    ]
