# Generated by Django 4.2.9 on 2024-01-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produts',
            new_name='Orders',
        ),
    ]
