# Generated by Django 5.0.2 on 2024-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_customuser_orders_product_delete_produts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='clientId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='productId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('Réapprovisionnement', 'Réapprovisionnement'), ('Urgence', 'Urgence'), ('Régulière Automatique', 'Régulière Automatique')], default='En ligne', max_length=200),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
