# Generated by Django 5.0.2 on 2024-02-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orders_clientid_alter_orders_productid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('Réapprovisionnement', 'Réapprovisionnement'), ('Urgence', 'Urgence'), ('Régulière Automatique', 'Régulière Automatique')], default='Réapprovisionnement', max_length=200),
        ),
    ]
